### ISSUE TITLE
Issue While Using the SDK-

### ISSUE THREAD

**Issue by avadoot-narvekar24** [oracle/oci-typescript-sdk#137]
Hi, I tried running one example under typescript(identity.js) . while running i am getting below error.

>reason: getaddrinfo EAI_AGAIN identity.us-ashburn-1.oci.oraclecloud.com
    at GenericRetrier.<anonymous> (c:\Codebase\oci-typescript-sdk-master\oci-typescript-sdk-master\lib\common\lib\retrier.ts:182:26)
    at Generator.throw (<anonymous>)
    at rejected (c:\Codebase\oci-typescript-sdk-master\oci-typescript-sdk-master\lib\common\lib\retrier.ts:10:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  statusCode: 'EAI_AGAIN',
  serviceCode: 'unknown code',
  opcRequestId: 'unknown'
}
Note: I have setup .oci\config details also under the home directory, 
Can somebody provide some insight on how to resolve this issue. Thanks

**Comment by jodoglevy** [comment]
Hi @avadoot-narvekar24 - EAI_AGAIN indicates a DNS lookup timed out - this is a network connectivity error or proxy related error, rather than an issue with the SDK code itself.

Some things to try to get more info:
- If you make an HTTPS request to identity.us-ashburn-1.oci.oraclecloud.com from another client (ex: curl) on the same box where this error occurred, does the request go through or also hit an error? If an error, what error?
- If you make an HTTPS request to a non-OCI URL (ex: https://google.com) from another client (ex: curl) on the same box where this error occurred, does the request go through or also hit an error? If an error, what error?
- If you make an HTTPS request to a non-OCI URL (ex: https://google.com) from typescript on the same box where this error occurred, does the request go through or also hit an error? If an error, what error?

**Comment by jodoglevy** [comment]
@avadoot-narvekar24 ping - did you still need help here? If we don't hear from you soon, we'll be closing this

**Comment by avadoot-narvekar24** [comment]
@jodoglevy , Hi, Thanks for your suggestions .  Yes it was  proxy issue , we were able to get it working. you can mark it as closed.
