### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by hiriumi** [oracle/oci-typescript-sdk#42]
I wrote an example to list instances for a compartment in a new branch.

I tried to push it but it was denied. My thought process of contributing is like this.

* Create a new branch locally.
* Work on the code. Test it locally.
* Commit the change.
* Push it and create a PR out of it.
* Get it reviewed.
* Make changes as necessary.
* PR gets approved.
* Merged to master.

How does your team accept PRs? Could someone explain it please?

**Comment by jodoglevy** [comment]
Hi @hiriumi ,

The reason your push failed is because you do not have write access to this GitHub repo, and you attempted to push directly to this repo. Instead, you should fork this repo, push your changes to that fork, and then issue a PR from your fork to this repo.

For more info see https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo and https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork.

**Comment by hiriumi** [comment]
Fork is the part I missed. I will try to do that. Thank you, @jodoglevy ! 👍
