### ISSUE TITLE
invokeFunctionHelper function is accepting request payload but not passing it in the request object

### ISSUE THREAD

**Issue by ramjiiyengar** [oracle/oci-typescript-sdk#88]
The correct code should pass the payload in the request object. Add the bolded line.

const request = {
    functionId: functionId,
    **invokeFunctionBody:   JSON.stringify(payload)**
}

**Comment by jodoglevy** [comment]
Thanks for reporting this @ramjiiyengar - we'll take a look and get back

**Comment by y-chandra** [comment]
@ramjiiyengar  - In this particular example, `payload` will always be a string since it's accessed from the environment variable. Hence, it doesn't help to add the above line in the code. Since, [invokeFunctionBody](https://github.com/oracle/oci-typescript-sdk/blob/9dd8eddf532b8f035ab50a6f6235a6ec5da4ec1d/lib/functions/lib/request/invoke-function-request.ts#L32)
only accepts `Uint8Array | Buffer | Blob | stream.Readable | ReadableStream | string`, the user should convert the request payload object to the appropriate format.

**Comment by y-chandra** [comment]
@ramjiiyengar  - Since the example works in the way it's intended to be used, we're going to close this issue. Feel free to reopen it if you face any issues.
